import {
  twoFactorAuthResolver,
  verifyTOTPResolver,
  systemUsersResolver,
  systemUserResolver,
  updateSystemUserResolver,
  deleteSystemUserResolver,
  studentsResolver,
  studentResolver,
  sendSystemUserRegistrationEmailResolver,
  sendStudentRegistrationEmailResolver,
  updateStudentResolver,
  createSystemUserResolver,
  createStudentResolver,
  createAnnouncementResolver,
  announcementsResolver,
  announcementResolver,
  updateAnnouncementResolver,
  deleteAnnouncementResolver,
  createMeetingResolver,
  createEventResolver,
  updateMeetingResolver,
  updateEventResolver,
  eventsResolver,
  eventResolver,
  meetingsResolver,
  meetingResolver,
  deleteEventResolver,
  deleteMeetingResolver,
  calendarEventsResolver,
  calendarMeetingsResolver,
  documentsResolver,
  createDocumentResolver,
  deleteDocumentResolver,
  updateDocumentResolver,
  createAllowanceResolver,
  updateAllowanceStatusResolver,
  allowancesResolver,
  allowanceResolver,
  monthlyEventsResolver,
  readStudentNotificationResolver,
  readAdminNotificationResolver,
  updateReadStudentNotificationResolver,
  updateReadAdminNotificationResolver,
  adminNotificationSubscription,
  scholarNotificationSubscription,
  createAdminNotificationResolver,
  createStudentNotificationResolver,
  dashboardOverviewDataResolver,
  transactionsResolver,
  lateSubmissionRequestsResolver,
  requestLateSubmissionResolver,
  approveLateSubmissionRequestResolver,
} from "./resolvers/index.js";

export const resolvers = {
  Subscription: {
    scholarNotificationSent: scholarNotificationSubscription,
    adminNotificationSent: adminNotificationSubscription,
  },
  Query: {
    lateSubmissionRequests: lateSubmissionRequestsResolver,
    transactions: transactionsResolver,
    generateTOTPSecret: twoFactorAuthResolver,
    systemUsers: systemUsersResolver,
    systemUser: systemUserResolver,
    students: studentsResolver,
    student: studentResolver,
    announcements: announcementsResolver,
    announcement: announcementResolver,
    events: eventsResolver,
    event: eventResolver,
    meetings: meetingsResolver,
    meeting: meetingResolver,
    calendarEvents: calendarEventsResolver,
    calendarMeetingEvents: calendarMeetingsResolver,
    documents: documentsResolver,
    allowances: allowancesResolver,
    allowance: allowanceResolver,
    monthlyEvents: monthlyEventsResolver,
    notifications: readStudentNotificationResolver,
    adminNotifications: readAdminNotificationResolver,
    dashboardOverviewData: dashboardOverviewDataResolver,
  },
  Mutation: {
    approveLateSubmissionRequest: approveLateSubmissionRequestResolver,
    requestLateSubmission: requestLateSubmissionResolver,
    verifyTOTP: verifyTOTPResolver,
    updateSystemUser: updateSystemUserResolver,
    deleteSystemUser: deleteSystemUserResolver,
    sendSystemUserRegistrationEmail: sendSystemUserRegistrationEmailResolver,
    sendStudentRegistrationEmail: sendStudentRegistrationEmailResolver,
    updateStudent: updateStudentResolver,
    createSystemUser: createSystemUserResolver,
    createStudent: createStudentResolver,
    createAnnouncement: createAnnouncementResolver,
    updateAnnouncement: updateAnnouncementResolver,
    deleteAnnouncement: deleteAnnouncementResolver,
    createMeeting: createMeetingResolver,
    createEvent: createEventResolver,
    updateMeeting: updateMeetingResolver,
    updateEvent: updateEventResolver,
    deleteEvent: deleteEventResolver,
    deleteMeeting: deleteMeetingResolver,
    createDocument: createDocumentResolver,
    deleteDocument: deleteDocumentResolver,
    updateDocument: updateDocumentResolver,
    createAllowance: createAllowanceResolver,
    updateAllowanceStatus: updateAllowanceStatusResolver,
    createAdminNotification: createAdminNotificationResolver,
    createScholarNotification: createStudentNotificationResolver,
    updateStudentNotification: updateReadStudentNotificationResolver,
    // updateAllStudentNotification: updateReadAllNotificationsResolver,

    // updateAllAdminNotification: updateReadAllAdminNotificationResolver,
    updateAdminNotification: updateReadAdminNotificationResolver,
  },
};
