import {
	twoFactorAuthResolver,
	verifyTOTPResolver,
	systemUsersResolver,
	systemUserResolver,
	updateSystemUserResolver,
	deleteSystemUserResolver,
	studentsResolver,
	studentResolver,
	sendSystemUserRegistrationEmailResolver,
	sendStudentRegistrationEmailResolver,
	updateStudentResolver,
	createSystemUserResolver,
	createStudentResolver,
	createAnnouncementResolver,
	announcementsResolver,
	announcementResolver,
	updateAnnouncementResolver,
	deleteAnnouncementResolver,
	createMeetingResolver,
	createEventResolver,
	updateMeetingResolver,
	updateEventResolver,
	eventsResolver,
	eventResolver,
	meetingsResolver,
	meetingResolver,
	deleteEventResolver,
	deleteMeetingResolver,
	calendarEventsResolver,
	calendarMeetingsResolver,
} from "./resolvers/index.js";

export const resolvers = {
	Query: {
		generateTOTPSecret: twoFactorAuthResolver,
		systemUsers: systemUsersResolver,
		systemUser: systemUserResolver,
		students: studentsResolver,
		student: studentResolver,
		announcements: announcementsResolver,
		announcement: announcementResolver,
		events: eventsResolver,
		event: eventResolver,
		meetings: meetingsResolver,
		meeting: meetingResolver,
		calendarEvents: calendarEventsResolver,
		calendarMeetingEvents: calendarMeetingsResolver,
	},
	Mutation: {
		verifyTOTP: verifyTOTPResolver,
		updateSystemUser: updateSystemUserResolver,
		deleteSystemUser: deleteSystemUserResolver,
		sendSystemUserRegistrationEmail: sendSystemUserRegistrationEmailResolver,
		sendStudentRegistrationEmail: sendStudentRegistrationEmailResolver,
		updateStudent: updateStudentResolver,
		createSystemUser: createSystemUserResolver,
		createStudent: createStudentResolver,
		createAnnouncement: createAnnouncementResolver,
		updateAnnouncement: updateAnnouncementResolver,
		deleteAnnouncement: deleteAnnouncementResolver,
		createMeeting: createMeetingResolver,
		createEvent: createEventResolver,
		updateMeeting: updateMeetingResolver,
		updateEvent: updateEventResolver,
		deleteEvent: deleteEventResolver,
		deleteMeeting: deleteMeetingResolver,
	},
};
